### PR TITLE
Setup ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
:smiley: 

(as commits says )

### CODE REVIEW

**Comment by kixxauth** [comment]
Excellent, thank you!

**Comment by AdrieanKhisbe** [comment]
@kixxauth you're welcome :)

**Comment by AdrieanKhisbe** [comment]
though seems I left a typo:

just replace `[coveralls-status]` by `[coveralls-url]` 
*sorry about this glitch*

**Comment by kixxauth** [comment]
Fixed the badge, and got a build: https://travis-ci.org/oddnetworks/oddcast

Yayy!

ships-shipping-ships-beta-032627232704

**Comment by AdrieanKhisbe** [comment]
:tada: !!

**Comment by AdrieanKhisbe** [comment]
you just have to activate coveralls, and :tada: :tada:

**Pull request merged**
